{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "468f4300",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Enter your word: hemanth\n",
      "Error: The Following Error occured: list index out of range\n",
      "None\n",
      "Enter your word: happy\n",
      "{'Adjective': ['enjoying or showing or marked by joy or pleasure', 'marked by good fortune', 'eagerly disposed to act or to be of service', 'well expressed and to the point']}\n"
     ]
    }
   ],
   "source": [
    "from PyDictionary import PyDictionary\n",
    "\n",
    "dictionary = PyDictionary()\n",
    "\n",
    "while True:\n",
    "    word = input(\"Enter your word: \")\n",
    "    if word == \"\":\n",
    "        break\n",
    "    \n",
    "    print(dictionary.meaning(word))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "be0a8d5f",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting PyDictionary\n",
      "  Downloading PyDictionary-2.0.1-py3-none-any.whl (6.1 kB)\n",
      "Collecting bs4\n",
      "  Downloading bs4-0.0.1.tar.gz (1.1 kB)\n",
      "Requirement already satisfied: click in c:\\users\\hemanth_s\\anaconda3\\lib\\site-packages (from PyDictionary) (8.0.3)\n",
      "Collecting goslate\n",
      "  Downloading goslate-1.5.4.tar.gz (14 kB)\n",
      "Requirement already satisfied: requests in c:\\users\\hemanth_s\\anaconda3\\lib\\site-packages (from PyDictionary) (2.26.0)\n",
      "Requirement already satisfied: beautifulsoup4 in c:\\users\\hemanth_s\\anaconda3\\lib\\site-packages (from bs4->PyDictionary) (4.10.0)\n",
      "Requirement already satisfied: soupsieve>1.2 in c:\\users\\hemanth_s\\anaconda3\\lib\\site-packages (from beautifulsoup4->bs4->PyDictionary) (2.2.1)\n",
      "Requirement already satisfied: colorama in c:\\users\\hemanth_s\\anaconda3\\lib\\site-packages (from click->PyDictionary) (0.4.4)\n",
      "Collecting futures\n",
      "  Downloading futures-3.0.5.tar.gz (25 kB)\n",
      "  Downloading futures-3.0.4.tar.gz (25 kB)\n",
      "  Downloading futures-3.0.3.tar.gz (24 kB)\n",
      "  Downloading futures-3.0.2.tar.gz (24 kB)\n",
      "  Downloading futures-3.0.1.tar.gz (24 kB)\n",
      "  Downloading futures-3.0.0.tar.gz (24 kB)\n",
      "  Downloading futures-2.2.0-py2.py3-none-any.whl (16 kB)\n",
      "Requirement already satisfied: idna<4,>=2.5 in c:\\users\\hemanth_s\\anaconda3\\lib\\site-packages (from requests->PyDictionary) (3.2)\n",
      "Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\\users\\hemanth_s\\anaconda3\\lib\\site-packages (from requests->PyDictionary) (1.26.7)\n",
      "Requirement already satisfied: charset-normalizer~=2.0.0 in c:\\users\\hemanth_s\\anaconda3\\lib\\site-packages (from requests->PyDictionary) (2.0.4)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in c:\\users\\hemanth_s\\anaconda3\\lib\\site-packages (from requests->PyDictionary) (2021.10.8)"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "    ERROR: Command errored out with exit status 1:\n",
      "     command: 'C:\\Users\\Hemanth_S\\anaconda3\\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\Hemanth_S\\\\AppData\\\\Local\\\\Temp\\\\pip-install-gl2f369z\\\\futures_1af7a22b96ad437f96d35e597a96e9ef\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\Hemanth_S\\\\AppData\\\\Local\\\\Temp\\\\pip-install-gl2f369z\\\\futures_1af7a22b96ad437f96d35e597a96e9ef\\\\setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base 'C:\\Users\\Hemanth_S\\AppData\\Local\\Temp\\pip-pip-egg-info-frt9d2wn'\n",
      "         cwd: C:\\Users\\Hemanth_S\\AppData\\Local\\Temp\\pip-install-gl2f369z\\futures_1af7a22b96ad437f96d35e597a96e9ef\\\n",
      "    Complete output (24 lines):\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"C:\\Users\\Hemanth_S\\anaconda3\\lib\\site-packages\\setuptools\\__init__.py\", line 18, in <module>\n",
      "        from setuptools.dist import Distribution\n",
      "      File \"C:\\Users\\Hemanth_S\\anaconda3\\lib\\site-packages\\setuptools\\dist.py\", line 32, in <module>\n",
      "        from setuptools.extern.more_itertools import unique_everseen\n",
      "      File \"<frozen importlib._bootstrap>\", line 1007, in _find_and_load\n",
      "      File \"<frozen importlib._bootstrap>\", line 986, in _find_and_load_unlocked\n",
      "      File \"<frozen importlib._bootstrap>\", line 666, in _load_unlocked\n",
      "      File \"<frozen importlib._bootstrap>\", line 565, in module_from_spec\n",
      "      File \"C:\\Users\\Hemanth_S\\anaconda3\\lib\\site-packages\\setuptools\\extern\\__init__.py\", line 52, in create_module\n",
      "        return self.load_module(spec.name)\n",
      "      File \"C:\\Users\\Hemanth_S\\anaconda3\\lib\\site-packages\\setuptools\\extern\\__init__.py\", line 37, in load_module\n",
      "        __import__(extant)\n",
      "      File \"C:\\Users\\Hemanth_S\\anaconda3\\lib\\site-packages\\setuptools\\_vendor\\more_itertools\\__init__.py\", line 1, in <module>\n",
      "        from .more import *  # noqa\n",
      "      File \"C:\\Users\\Hemanth_S\\anaconda3\\lib\\site-packages\\setuptools\\_vendor\\more_itertools\\more.py\", line 5, in <module>\n",
      "        from concurrent.futures import ThreadPoolExecutor\n",
      "      File \"C:\\Users\\Hemanth_S\\AppData\\Local\\Temp\\pip-install-gl2f369z\\futures_1af7a22b96ad437f96d35e597a96e9ef\\concurrent\\futures\\__init__.py\", line 8, in <module>\n",
      "        from concurrent.futures._base import (FIRST_COMPLETED,\n",
      "      File \"C:\\Users\\Hemanth_S\\AppData\\Local\\Temp\\pip-install-gl2f369z\\futures_1af7a22b96ad437f96d35e597a96e9ef\\concurrent\\futures\\_base.py\", line 357\n",
      "        raise type(self._exception), self._exception, self._traceback\n",
      "                                   ^\n",
      "    SyntaxError: invalid syntax\n",
      "    ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/55/db/97c1ca37edab586a1ae03d6892b6633d8eaa23b23ac40c7e5bbc55423c78/futures-3.0.5.tar.gz#sha256=0542525145d5afc984c88f914a0c85c77527f65946617edb5274f72406f981df (from https://pypi.org/simple/futures/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\n",
      "    ERROR: Command errored out with exit status 1:\n",
      "     command: 'C:\\Users\\Hemanth_S\\anaconda3\\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\Hemanth_S\\\\AppData\\\\Local\\\\Temp\\\\pip-install-gl2f369z\\\\futures_a31bd30e557b48ebaae97c686def9a9c\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\Hemanth_S\\\\AppData\\\\Local\\\\Temp\\\\pip-install-gl2f369z\\\\futures_a31bd30e557b48ebaae97c686def9a9c\\\\setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base 'C:\\Users\\Hemanth_S\\AppData\\Local\\Temp\\pip-pip-egg-info-t465ehec'\n",
      "         cwd: C:\\Users\\Hemanth_S\\AppData\\Local\\Temp\\pip-install-gl2f369z\\futures_a31bd30e557b48ebaae97c686def9a9c\\\n",
      "    Complete output (24 lines):\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"C:\\Users\\Hemanth_S\\anaconda3\\lib\\site-packages\\setuptools\\__init__.py\", line 18, in <module>\n",
      "        from setuptools.dist import Distribution\n",
      "      File \"C:\\Users\\Hemanth_S\\anaconda3\\lib\\site-packages\\setuptools\\dist.py\", line 32, in <module>\n",
      "        from setuptools.extern.more_itertools import unique_everseen\n",
      "      File \"<frozen importlib._bootstrap>\", line 1007, in _find_and_load\n",
      "      File \"<frozen importlib._bootstrap>\", line 986, in _find_and_load_unlocked\n",
      "      File \"<frozen importlib._bootstrap>\", line 666, in _load_unlocked\n",
      "      File \"<frozen importlib._bootstrap>\", line 565, in module_from_spec\n",
      "      File \"C:\\Users\\Hemanth_S\\anaconda3\\lib\\site-packages\\setuptools\\extern\\__init__.py\", line 52, in create_module\n",
      "        return self.load_module(spec.name)\n",
      "      File \"C:\\Users\\Hemanth_S\\anaconda3\\lib\\site-packages\\setuptools\\extern\\__init__.py\", line 37, in load_module\n",
      "        __import__(extant)\n",
      "      File \"C:\\Users\\Hemanth_S\\anaconda3\\lib\\site-packages\\setuptools\\_vendor\\more_itertools\\__init__.py\", line 1, in <module>\n",
      "        from .more import *  # noqa\n",
      "      File \"C:\\Users\\Hemanth_S\\anaconda3\\lib\\site-packages\\setuptools\\_vendor\\more_itertools\\more.py\", line 5, in <module>\n",
      "        from concurrent.futures import ThreadPoolExecutor\n",
      "      File \"C:\\Users\\Hemanth_S\\AppData\\Local\\Temp\\pip-install-gl2f369z\\futures_a31bd30e557b48ebaae97c686def9a9c\\concurrent\\futures\\__init__.py\", line 8, in <module>\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Building wheels for collected packages: bs4, goslate\n",
      "  Building wheel for bs4 (setup.py): started\n",
      "  Building wheel for bs4 (setup.py): finished with status 'done'\n",
      "  Created wheel for bs4: filename=bs4-0.0.1-py3-none-any.whl size=1271 sha256=56b5e9badf4242d6efa0d104d0a18e43c179ddd86b64ee875d41ba6b19cf71b1\n",
      "  Stored in directory: c:\\users\\hemanth_s\\appdata\\local\\pip\\cache\\wheels\\73\\2b\\cb\\099980278a0c9a3e57ff1a89875ec07bfa0b6fcbebb9a8cad3\n",
      "  Building wheel for goslate (setup.py): started\n",
      "  Building wheel for goslate (setup.py): finished with status 'done'\n",
      "  Created wheel for goslate: filename=goslate-1.5.4-py3-none-any.whl size=11595 sha256=420ec95edad31f52e027f630d41321dae47824169ced9dccce1003312c132d5c\n",
      "  Stored in directory: c:\\users\\hemanth_s\\appdata\\local\\pip\\cache\\wheels\\ee\\5c\\9a\\23d357c94b883bb9b9928aa61fa98641ac1635d5df3dd4dfef\n",
      "Successfully built bs4 goslate\n",
      "Installing collected packages: futures, goslate, bs4, PyDictionary\n",
      "Successfully installed PyDictionary-2.0.1 bs4-0.0.1 futures-2.2.0 goslate-1.5.4\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "        from concurrent.futures._base import (FIRST_COMPLETED,\n",
      "      File \"C:\\Users\\Hemanth_S\\AppData\\Local\\Temp\\pip-install-gl2f369z\\futures_a31bd30e557b48ebaae97c686def9a9c\\concurrent\\futures\\_base.py\", line 357\n",
      "        raise type(self._exception), self._exception, self._traceback\n",
      "                                   ^\n",
      "    SyntaxError: invalid syntax\n",
      "    ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/8d/73/b5fff618482bc06c9711e7cdc0d5d7eb1904d35898f48f2d7f9696b08bef/futures-3.0.4.tar.gz#sha256=19485d83f7bd2151c0aeaf88fbba3ee50dadfb222ffc3b66a344ef4952b782a3 (from https://pypi.org/simple/futures/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\n",
      "    ERROR: Command errored out with exit status 1:\n",
      "     command: 'C:\\Users\\Hemanth_S\\anaconda3\\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\Hemanth_S\\\\AppData\\\\Local\\\\Temp\\\\pip-install-gl2f369z\\\\futures_c64be037942a4b53a292651e8b19fef7\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\Hemanth_S\\\\AppData\\\\Local\\\\Temp\\\\pip-install-gl2f369z\\\\futures_c64be037942a4b53a292651e8b19fef7\\\\setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base 'C:\\Users\\Hemanth_S\\AppData\\Local\\Temp\\pip-pip-egg-info-d3z9sniu'\n",
      "         cwd: C:\\Users\\Hemanth_S\\AppData\\Local\\Temp\\pip-install-gl2f369z\\futures_c64be037942a4b53a292651e8b19fef7\\\n",
      "    Complete output (24 lines):\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"C:\\Users\\Hemanth_S\\anaconda3\\lib\\site-packages\\setuptools\\__init__.py\", line 18, in <module>\n",
      "        from setuptools.dist import Distribution\n",
      "      File \"C:\\Users\\Hemanth_S\\anaconda3\\lib\\site-packages\\setuptools\\dist.py\", line 32, in <module>\n",
      "        from setuptools.extern.more_itertools import unique_everseen\n",
      "      File \"<frozen importlib._bootstrap>\", line 1007, in _find_and_load\n",
      "      File \"<frozen importlib._bootstrap>\", line 986, in _find_and_load_unlocked\n",
      "      File \"<frozen importlib._bootstrap>\", line 666, in _load_unlocked\n",
      "      File \"<frozen importlib._bootstrap>\", line 565, in module_from_spec\n",
      "      File \"C:\\Users\\Hemanth_S\\anaconda3\\lib\\site-packages\\setuptools\\extern\\__init__.py\", line 52, in create_module\n",
      "        return self.load_module(spec.name)\n",
      "      File \"C:\\Users\\Hemanth_S\\anaconda3\\lib\\site-packages\\setuptools\\extern\\__init__.py\", line 37, in load_module\n",
      "        __import__(extant)\n",
      "      File \"C:\\Users\\Hemanth_S\\anaconda3\\lib\\site-packages\\setuptools\\_vendor\\more_itertools\\__init__.py\", line 1, in <module>\n",
      "        from .more import *  # noqa\n",
      "      File \"C:\\Users\\Hemanth_S\\anaconda3\\lib\\site-packages\\setuptools\\_vendor\\more_itertools\\more.py\", line 5, in <module>\n",
      "        from concurrent.futures import ThreadPoolExecutor\n",
      "      File \"C:\\Users\\Hemanth_S\\AppData\\Local\\Temp\\pip-install-gl2f369z\\futures_c64be037942a4b53a292651e8b19fef7\\concurrent\\futures\\__init__.py\", line 8, in <module>\n",
      "        from concurrent.futures._base import (FIRST_COMPLETED,\n",
      "      File \"C:\\Users\\Hemanth_S\\AppData\\Local\\Temp\\pip-install-gl2f369z\\futures_c64be037942a4b53a292651e8b19fef7\\concurrent\\futures\\_base.py\", line 355\n",
      "        raise type(self._exception), self._exception, self._traceback\n",
      "                                   ^\n",
      "    SyntaxError: invalid syntax\n",
      "    ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/4c/dc/f9473006d4c9c52d4a4e977173fbcbfb1a8ef3a57e32e885edf994fd4a45/futures-3.0.3.tar.gz#sha256=2fe2342bb4fe8b8e217f0d21b5921cbe5408bf966d9f92025e707e881b198bed (from https://pypi.org/simple/futures/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\n",
      "    ERROR: Command errored out with exit status 1:\n",
      "     command: 'C:\\Users\\Hemanth_S\\anaconda3\\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\Hemanth_S\\\\AppData\\\\Local\\\\Temp\\\\pip-install-gl2f369z\\\\futures_de34f5cfea7e455e864d19d3a2eced72\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\Hemanth_S\\\\AppData\\\\Local\\\\Temp\\\\pip-install-gl2f369z\\\\futures_de34f5cfea7e455e864d19d3a2eced72\\\\setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base 'C:\\Users\\Hemanth_S\\AppData\\Local\\Temp\\pip-pip-egg-info-6d3kaoeb'\n",
      "         cwd: C:\\Users\\Hemanth_S\\AppData\\Local\\Temp\\pip-install-gl2f369z\\futures_de34f5cfea7e455e864d19d3a2eced72\\\n",
      "    Complete output (24 lines):\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"C:\\Users\\Hemanth_S\\anaconda3\\lib\\site-packages\\setuptools\\__init__.py\", line 18, in <module>\n",
      "        from setuptools.dist import Distribution\n",
      "      File \"C:\\Users\\Hemanth_S\\anaconda3\\lib\\site-packages\\setuptools\\dist.py\", line 32, in <module>\n",
      "        from setuptools.extern.more_itertools import unique_everseen\n",
      "      File \"<frozen importlib._bootstrap>\", line 1007, in _find_and_load\n",
      "      File \"<frozen importlib._bootstrap>\", line 986, in _find_and_load_unlocked\n",
      "      File \"<frozen importlib._bootstrap>\", line 666, in _load_unlocked\n",
      "      File \"<frozen importlib._bootstrap>\", line 565, in module_from_spec\n",
      "      File \"C:\\Users\\Hemanth_S\\anaconda3\\lib\\site-packages\\setuptools\\extern\\__init__.py\", line 52, in create_module\n",
      "        return self.load_module(spec.name)\n",
      "      File \"C:\\Users\\Hemanth_S\\anaconda3\\lib\\site-packages\\setuptools\\extern\\__init__.py\", line 37, in load_module\n",
      "        __import__(extant)\n",
      "      File \"C:\\Users\\Hemanth_S\\anaconda3\\lib\\site-packages\\setuptools\\_vendor\\more_itertools\\__init__.py\", line 1, in <module>\n",
      "        from .more import *  # noqa\n",
      "      File \"C:\\Users\\Hemanth_S\\anaconda3\\lib\\site-packages\\setuptools\\_vendor\\more_itertools\\more.py\", line 5, in <module>\n",
      "        from concurrent.futures import ThreadPoolExecutor\n",
      "      File \"C:\\Users\\Hemanth_S\\AppData\\Local\\Temp\\pip-install-gl2f369z\\futures_de34f5cfea7e455e864d19d3a2eced72\\concurrent\\futures\\__init__.py\", line 8, in <module>\n",
      "        from concurrent.futures._base import (FIRST_COMPLETED,\n",
      "      File \"C:\\Users\\Hemanth_S\\AppData\\Local\\Temp\\pip-install-gl2f369z\\futures_de34f5cfea7e455e864d19d3a2eced72\\concurrent\\futures\\_base.py\", line 355\n",
      "        raise type(self._exception), self._exception, self._traceback\n",
      "                                   ^\n",
      "    SyntaxError: invalid syntax\n",
      "    ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/f8/e7/fc0fcbeb9193ba2d4de00b065e7fd5aecd0679e93ce95a07322b2b1434f4/futures-3.0.2.tar.gz#sha256=dc3fc91508e49e0fd2f8625f0132d16e49c80f882e7e1d565c56b0d5dfbae257 (from https://pypi.org/simple/futures/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\n",
      "    ERROR: Command errored out with exit status 1:\n",
      "     command: 'C:\\Users\\Hemanth_S\\anaconda3\\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\Hemanth_S\\\\AppData\\\\Local\\\\Temp\\\\pip-install-gl2f369z\\\\futures_6a1ac13df2d24b92a5db50038d7af3a7\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\Hemanth_S\\\\AppData\\\\Local\\\\Temp\\\\pip-install-gl2f369z\\\\futures_6a1ac13df2d24b92a5db50038d7af3a7\\\\setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base 'C:\\Users\\Hemanth_S\\AppData\\Local\\Temp\\pip-pip-egg-info-yds53prk'\n",
      "         cwd: C:\\Users\\Hemanth_S\\AppData\\Local\\Temp\\pip-install-gl2f369z\\futures_6a1ac13df2d24b92a5db50038d7af3a7\\\n",
      "    Complete output (24 lines):\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"C:\\Users\\Hemanth_S\\anaconda3\\lib\\site-packages\\setuptools\\__init__.py\", line 18, in <module>\n",
      "        from setuptools.dist import Distribution\n",
      "      File \"C:\\Users\\Hemanth_S\\anaconda3\\lib\\site-packages\\setuptools\\dist.py\", line 32, in <module>\n",
      "        from setuptools.extern.more_itertools import unique_everseen\n",
      "      File \"<frozen importlib._bootstrap>\", line 1007, in _find_and_load\n",
      "      File \"<frozen importlib._bootstrap>\", line 986, in _find_and_load_unlocked\n",
      "      File \"<frozen importlib._bootstrap>\", line 666, in _load_unlocked\n",
      "      File \"<frozen importlib._bootstrap>\", line 565, in module_from_spec\n",
      "      File \"C:\\Users\\Hemanth_S\\anaconda3\\lib\\site-packages\\setuptools\\extern\\__init__.py\", line 52, in create_module\n",
      "        return self.load_module(spec.name)\n",
      "      File \"C:\\Users\\Hemanth_S\\anaconda3\\lib\\site-packages\\setuptools\\extern\\__init__.py\", line 37, in load_module\n",
      "        __import__(extant)\n",
      "      File \"C:\\Users\\Hemanth_S\\anaconda3\\lib\\site-packages\\setuptools\\_vendor\\more_itertools\\__init__.py\", line 1, in <module>\n",
      "        from .more import *  # noqa\n",
      "      File \"C:\\Users\\Hemanth_S\\anaconda3\\lib\\site-packages\\setuptools\\_vendor\\more_itertools\\more.py\", line 5, in <module>\n",
      "        from concurrent.futures import ThreadPoolExecutor\n",
      "      File \"C:\\Users\\Hemanth_S\\AppData\\Local\\Temp\\pip-install-gl2f369z\\futures_6a1ac13df2d24b92a5db50038d7af3a7\\concurrent\\futures\\__init__.py\", line 8, in <module>\n",
      "        from concurrent.futures._base import (FIRST_COMPLETED,\n",
      "      File \"C:\\Users\\Hemanth_S\\AppData\\Local\\Temp\\pip-install-gl2f369z\\futures_6a1ac13df2d24b92a5db50038d7af3a7\\concurrent\\futures\\_base.py\", line 355\n",
      "        raise type(self._exception), self._exception, self._traceback\n",
      "                                   ^\n",
      "    SyntaxError: invalid syntax\n",
      "    ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/b2/2c/6b6a57379e47031c6f52e625e0e2b8f6702a8d1f61b6e0daee391e82c187/futures-3.0.1.tar.gz#sha256=f78f2ef458639d72a625cf9c7643cf5442bb222ac11c12bcc445c6ad1cd862e2 (from https://pypi.org/simple/futures/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\n",
      "    ERROR: Command errored out with exit status 1:\n",
      "     command: 'C:\\Users\\Hemanth_S\\anaconda3\\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\Hemanth_S\\\\AppData\\\\Local\\\\Temp\\\\pip-install-gl2f369z\\\\futures_ddb9a9aca7af40fba19c63e1a15232ee\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\Hemanth_S\\\\AppData\\\\Local\\\\Temp\\\\pip-install-gl2f369z\\\\futures_ddb9a9aca7af40fba19c63e1a15232ee\\\\setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base 'C:\\Users\\Hemanth_S\\AppData\\Local\\Temp\\pip-pip-egg-info-eqb3u9en'\n",
      "         cwd: C:\\Users\\Hemanth_S\\AppData\\Local\\Temp\\pip-install-gl2f369z\\futures_ddb9a9aca7af40fba19c63e1a15232ee\\\n",
      "    Complete output (24 lines):\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"C:\\Users\\Hemanth_S\\anaconda3\\lib\\site-packages\\setuptools\\__init__.py\", line 18, in <module>\n",
      "        from setuptools.dist import Distribution\n",
      "      File \"C:\\Users\\Hemanth_S\\anaconda3\\lib\\site-packages\\setuptools\\dist.py\", line 32, in <module>\n",
      "        from setuptools.extern.more_itertools import unique_everseen\n",
      "      File \"<frozen importlib._bootstrap>\", line 1007, in _find_and_load\n",
      "      File \"<frozen importlib._bootstrap>\", line 986, in _find_and_load_unlocked\n",
      "      File \"<frozen importlib._bootstrap>\", line 666, in _load_unlocked\n",
      "      File \"<frozen importlib._bootstrap>\", line 565, in module_from_spec\n",
      "      File \"C:\\Users\\Hemanth_S\\anaconda3\\lib\\site-packages\\setuptools\\extern\\__init__.py\", line 52, in create_module\n",
      "        return self.load_module(spec.name)\n",
      "      File \"C:\\Users\\Hemanth_S\\anaconda3\\lib\\site-packages\\setuptools\\extern\\__init__.py\", line 37, in load_module\n",
      "        __import__(extant)\n",
      "      File \"C:\\Users\\Hemanth_S\\anaconda3\\lib\\site-packages\\setuptools\\_vendor\\more_itertools\\__init__.py\", line 1, in <module>\n",
      "        from .more import *  # noqa\n",
      "      File \"C:\\Users\\Hemanth_S\\anaconda3\\lib\\site-packages\\setuptools\\_vendor\\more_itertools\\more.py\", line 5, in <module>\n",
      "        from concurrent.futures import ThreadPoolExecutor\n",
      "      File \"C:\\Users\\Hemanth_S\\AppData\\Local\\Temp\\pip-install-gl2f369z\\futures_ddb9a9aca7af40fba19c63e1a15232ee\\concurrent\\futures\\__init__.py\", line 8, in <module>\n",
      "        from concurrent.futures._base import (FIRST_COMPLETED,\n",
      "      File \"C:\\Users\\Hemanth_S\\AppData\\Local\\Temp\\pip-install-gl2f369z\\futures_ddb9a9aca7af40fba19c63e1a15232ee\\concurrent\\futures\\_base.py\", line 354\n",
      "        raise type(self._exception), self._exception, self._traceback\n",
      "                                   ^\n",
      "    SyntaxError: invalid syntax\n",
      "    ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/ea/c9/35287369718fc05059e7a9d0d73c53745fe981010b4185b3858e7d46eff1/futures-3.0.0.tar.gz#sha256=d9cd7bb09aa01f0e4940af64c31fbd7045098b7b4354420d7838ea39e8b86ee3 (from https://pypi.org/simple/futures/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\n"
     ]
    }
   ],
   "source": [
    "!pip install PyDictionary"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
